name: AutoPEP8 Formatter

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.5'  # Cambia a la versión de Python que estés utilizando

    - name: Install autopep8
      run: pip install autopep8

    - name: Run autopep8
      run: autopep8 --in-place --aggressive --aggressive --recursive .

    - name: Check for style violations
      run: |
        git diff --exit-code || (
          echo "autopep8 encontro problemas" &&
          echo "Committing changes" &&
          git config --global user.email "action@github.com" &&
          git config --global user.name "GitHub Action" &&
          git add . &&
          git commit -m "style: autopep8 fixes" &&
          git push
        )
