name: AutoPEP8 Formatter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  autopep8:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install autopep8

    - name: Run autopep8
      run: |
        autopep8 --exit-code --recursive --in-place --aggressive --aggressive .

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'github-actions'
        author_email: 'github-actions@github.com'
        message: 'Apply autopep8 formatting'
        add: '.'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
